import { Router, type IRouter } from "express";
import healthRouter from "./health";
import projectsRouter from "./projects";
import companiesRouter from "./companies";
import adminRouter from "./admin";
import adminAuthRouter from "./admin-auth";
import authRouter from "./auth";
import userAuthRouter from "./user-auth";
import chatRouter from "./chat";
import contactRouter from "./contact";
import storageRouter from "./storage";
import portfolioRouter from "./portfolio";
import publicProfileRouter from "./public-profile";
import billingRouter from "./billing";
import offersRouter from "./offers";
import adminBillingRouter from "./admin-billing";
import reviewsRouter from "./reviews";
import messagesRouter from "./messages";

const router: IRouter = Router();

router.use(healthRouter);
router.use(projectsRouter);
router.use(companiesRouter);
router.use(authRouter);
router.use(userAuthRouter);
router.use(adminAuthRouter);
router.use(adminRouter);
router.use(chatRouter);
router.use(contactRouter);
router.use(storageRouter);
router.use(portfolioRouter);
router.use(publicProfileRouter);
router.use(billingRouter);
router.use(offersRouter);
router.use(adminBillingRouter);
router.use(reviewsRouter);
router.use(messagesRouter);

export default router;
